### ISSUE TITLE
Add support for Eclipse 2023-06 (v4.28) platform

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#418]
## Checklists
(From https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Fix-Release-Checklist)
### Dependencies
* [x] Update LCLS Dep  **(upgrade to v2.0.1)**
* [x] Update LSP4MP? **(no, remain on v0.7)**
* [x] Update LSP4Jakarta?  **(no, remain on v0.1.1)**
* [x] Update lsp4e/lsp4j deps?    
* [x] Update jdtls deps?    
* [x] Update other Category.xml / feature.xml deps?
### Tracking
* [x] Release Plan - https://github.com/orgs/openLiberty/projects/21
* [x] Milestone  - https://github.com/OpenLiberty/liberty-tools-eclipse/milestone/4
* [x] Epic
### Test Level
* [x] target platform file
* [x] default level in POM
* [x] default level GHA
* [x] default level Jenkins
* [x] Better to test vs. multiple levels in any of these envs or just one?
* [x] Test LCLS 2.0.1 delta
### Other releng 
(See https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Release-build-process)
* [x] Mend/Whitesource scan (see instructions in  ci/scans/dependency-only-mend-pom.xml)
* [x] Static app scan
* [x] Doc updates
* [x] Update changelog
