### ISSUE TITLE
Add support for Eclipse 2023-09 (v4.29) platform 

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#452]
## Checklists
(From https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Fix-Release-Checklist)
### Dependencies
* [x] Update LCLS Dep
* [x] Update LSP4MP?
* [x] Update LSP4Jakarta?
* [x] Update lsp4e/lsp4j deps?    
* [x] Update jdtls deps?    
* [x] Update other Category.xml / feature.xml deps?
### Tracking
* [x] Release Plan - https://github.com/orgs/openLiberty/projects/21
* [x] Milestone  - https://github.com/OpenLiberty/liberty-tools-eclipse/milestone/5
* [x] Epic
### Test Level
* [x] target platform file (copy from last version, update URLs, Ctrl+Space to populate new versions, try to align version with target Eclipse install like with Mend scan contents)
* [x] default level in POM
* [x] default level GHA
* [x] default level Jenkins
* [x] Better to test vs. multiple levels in any of these envs or just one?
### Other releng 
(See https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Release-build-process)
* [x] Mend/Whitesource scan (see instructions in  ci/scans/dependency-only-mend-pom.xml)
* [x] Static app scan
* [x] Update NOTICE file after dep scan
* [x] Doc update
* [x] Eclipse Marketplace entry
* [x] Update [CHANGELOG.md](https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/CHANGELOG.md)
