### ISSUE TITLE
Add support including test target platform for Eclipse 2023-12 (v4.30) platform

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#486]
## NOTE

This is a bit of a different case vs. the past, in that our LTE 23.0.12 release already had enough testing against Eclipse 2023-12 that we declared support for this in Eclipse Marketplace and our doc.

Still, we want to go through the same process as usual, creating the new target platform and running tests against it, reviewing dependency version, etc. 

## Checklists
(From https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Fix-Release-Checklist)
### Dependencies
* [x] Update LCLS Dep
* [x] Update LSP4MP?
* [x] Update LSP4Jakarta?
* [x] Update lsp4e/lsp4j deps?     Probably each quarter we should assume we use the quarterly update in the Eclipse release (whether it comes from the platform itself or another bundled component like WWD) as a starting point. But sometimes because of bugs we need to use a custom, newer (or older?) version. Sometimes we might follow the JBoss/Quarkus or lsp4mp leads. Don't assume though that because we used a custom version last quarter that we either want to use a new custom one or keep the version the same this quarter. Again, the version you get with the vanilla Eclipse package install is a good starting point each quarter.
* [x] Update jdtls deps?    (Similar to lsp4e/lsp4j)
* [x] Update other Category.xml / feature.xml deps?
### Tracking
* [x] Milestone  - e.g. https://github.com/OpenLiberty/liberty-tools-eclipse/milestone/4
* [x] Release Plan - https://github.com/orgs/openLiberty/projects/21  (make sure it includes the Milestone highlights so we can bubble up the most important elements to a broader view of Liberty Tools / DevEx work).
* [x] Epic issue (this issue)
### Test Level
* [x] target platform file (copy from last version, update URLs, Ctrl+Space to populate new versions, try to align version with target Eclipse install like with Mend scan contents)
* [x] default level in POM
* [x] default level GHA
* [ ] default level Jenkins
* [x] Better to test vs. multiple levels in any of these envs or just one?
* [x] Manual test against latest release (N+1), e.g. Eclipse 2024-03 for LTE 24.0.3
### Other releng 
(See https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Release-build-process)
* [x] Mend/Whitesource scan (see instructions in  ci/scans/dependency-only-mend-pom.xml)
* [x] Static app scan
* [x] Update NOTICE file after dep scan
* [x] Doc update
* [x] Eclipse Marketplace entry
* [x] Update [CHANGELOG.md](https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/CHANGELOG.md).  (Try GH 'compare', e.g. [this](https://github.com/OpenLiberty/liberty-tools-eclipse/compare/liberty-tools-23.0.9.202309271814...liberty-tools-23.0.12.202311281452).)
* [x] FINALLY - tag/release in Git/GitHub
